# Generated by Django 4.1.2 on 2022-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_alter_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=250, verbose_name="Текст"),
        ),
    ]
