# Generated by Django 4.1.2 on 2022-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0008_alter_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_num",
            field=models.IntegerField(default=1),
        ),
    ]
